// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieRecommendationAPI.Data;

#nullable disable

namespace MovieRecommendationAPI.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("MovieRecommendationAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("user_id");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER")
                        .HasColumnName("age");

                    b.Property<int?>("AmazonPrime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Amazon Prime");

                    b.Property<int?>("AppleTVPlus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Apple TV+");

                    b.Property<string>("City")
                        .HasColumnType("TEXT")
                        .HasColumnName("city");

                    b.Property<int?>("DisneyPlus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Disney+");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT")
                        .HasColumnName("gender");

                    b.Property<int?>("Hulu")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Hulu");

                    b.Property<int?>("Max")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Max");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int?>("Netflix")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Netflix");

                    b.Property<int?>("ParamountPlus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Paramount+");

                    b.Property<int?>("Peacock")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Peacock");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.Property<string>("State")
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.Property<int?>("Zip")
                        .HasColumnType("INTEGER")
                        .HasColumnName("zip");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("movies_users");
                });
#pragma warning restore 612, 618
        }
    }
}
